import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

const List<Map<String, String>> countryData = [
  {'code': 'US', 'dialCode': '+1', 'flag': '🇺🇸'},
  {'code': 'CA', 'dialCode': '+1', 'flag': '🇨🇦'},
  {'code': 'GB', 'dialCode': '+44', 'flag': '🇬🇧'},
  {'code': 'AU', 'dialCode': '+61', 'flag': '🇦🇺'},
  {'code': 'DE', 'dialCode': '+49', 'flag': '🇩🇪'},
  {'code': 'IN', 'dialCode': '+91', 'flag': '🇮🇳'},
  {'code': 'JP', 'dialCode': '+81', 'flag': '🇯🇵'},
  {'code': 'CN', 'dialCode': '+86', 'flag': '🇨🇳'},
  {'code': 'FR', 'dialCode': '+33', 'flag': '🇫🇷'},
  {'code': 'IT', 'dialCode': '+39', 'flag': '🇮🇹'},
  {'code': 'ES', 'dialCode': '+34', 'flag': '🇪🇸'},
  {'code': 'BR', 'dialCode': '+55', 'flag': '🇧🇷'},
  {'code': 'ZA', 'dialCode': '+27', 'flag': '🇿🇦'},
  {'code': 'NG', 'dialCode': '+234', 'flag': '🇳🇬'},
  {'code': 'MX', 'dialCode': '+52', 'flag': '🇲🇽'},
  {'code': 'RU', 'dialCode': '+7', 'flag': '🇷🇺'},
  {'code': 'KR', 'dialCode': '+82', 'flag': '🇰🇷'},
  {'code': 'SA', 'dialCode': '+966', 'flag': '🇸🇦'},
  {'code': 'AR', 'dialCode': '+54', 'flag': '🇦🇷'},
  {'code': 'NL', 'dialCode': '+31', 'flag': '🇳🇱'},
  {'code': 'SE', 'dialCode': '+46', 'flag': '🇸🇪'},
  {'code': 'CH', 'dialCode': '+41', 'flag': '🇨🇭'},
  {'code': 'BE', 'dialCode': '+32', 'flag': '🇧🇪'},
  {'code': 'AT', 'dialCode': '+43', 'flag': '🇦🇹'},
  {'code': 'FI', 'dialCode': '+358', 'flag': '🇫🇮'},
  {'code': 'DK', 'dialCode': '+45', 'flag': '🇩🇰'},
  {'code': 'NO', 'dialCode': '+47', 'flag': '🇳🇴'},
  {'code': 'PL', 'dialCode': '+48', 'flag': '🇵🇱'},
  {'code': 'PT', 'dialCode': '+351', 'flag': '🇵🇹'},
  {'code': 'GR', 'dialCode': '+30', 'flag': '🇬🇷'},
  {'code': 'TR', 'dialCode': '+90', 'flag': '🇹🇷'},
  {'code': 'EG', 'dialCode': '+20', 'flag': '🇪🇬'},
  {'code': 'KE', 'dialCode': '+254', 'flag': '🇰🇪'},
  {'code': 'TH', 'dialCode': '+66', 'flag': '🇹🇭'},
  {'code': 'VN', 'dialCode': '+84', 'flag': '🇻🇳'},
  {'code': 'PH', 'dialCode': '+63', 'flag': '🇵🇭'},
  {'code': 'MY', 'dialCode': '+60', 'flag': '🇲🇾'},
  {'code': 'SG', 'dialCode': '+65', 'flag': '🇸🇬'},
];

const List<String> services = [
  "Artists",
  "Event Spaces",
  "Catering Companies",
  "Interior Decoration Companies",
  "Car Rental Companies",
  "Photographers",
  "Makeup",
  "Hairdressing/Barber",
  "Podium/Lighting Setup Companies",
  "Tent Rental Companies",
  "Wedding Gifts, Presents, Favors",
  "Tailoring Workshops, Fashion, etc",
  "Alcohol Suppliers, Cigars, Bars",
  "Flowers, Bouquets",
  "Others",
];

List<String> getLocalizedServices(BuildContext context) {
  return [
    AppLocalizations.of(context)!.serviceArtists,
    AppLocalizations.of(context)!.serviceEventSpaces,
    AppLocalizations.of(context)!.serviceCateringCompanies,
    AppLocalizations.of(context)!.serviceInteriorDecorators,
    AppLocalizations.of(context)!.serviceCarRental,
    AppLocalizations.of(context)!.servicePhotographers,
    AppLocalizations.of(context)!.serviceMakeup,
    AppLocalizations.of(context)!.serviceHairdressing,
    AppLocalizations.of(context)!.servicePodiumLighting,
    AppLocalizations.of(context)!.serviceTentRental,
    AppLocalizations.of(context)!.serviceWeddingGifts,
    AppLocalizations.of(context)!.serviceTailoringFashion,
    AppLocalizations.of(context)!.serviceAlcoholSuppliers,
    AppLocalizations.of(context)!.serviceFlowersBouquets,
    AppLocalizations.of(context)!.serviceOthers,
  ];
}